### ISSUE TITLE
Paypal.ERROR_USER_CANCELED   back a white page

### ISSUE THREAD

**Issue by 277850318** [narayananvenk/react-native-paypal#1]
if(error=Paypal.ERROR_USER_CANCELED ){
   navigator.pop();  
// this can not  back  to   i  start pay page,with a white page
//must press back key again for the right page
//how can i do?
}

**Comment by narayananvenk** [comment]
Does this happen for both iOS and Android? Also, which version of react native are you using?

**Comment by 277850318** [comment]
is my problem
