### ISSUE TITLE
ios not for react native

### ISSUE THREAD

**Issue by 277850318** [narayananvenk/react-native-paypal#3]
ios not for react native

**Comment by narayananvenk** [comment]
What does this mean? Are you unable to setup the iOS version of this module?

**Comment by 277850318** [comment]
i do not known how to setup ios  on  step 2 and
 3;can you description more detail

**Comment by narayananvenk** [comment]
1. This should already be complete (adding the module as a dependency to package.json) since you have setup this module for android.
2. Can you try using [this](https://developer.apple.com/library/ios/recipes/xcode_help-structure_navigator/articles/Adding_an_Existing_File_or_Folder.html)?

**Comment by 277850318** [comment]
![image](https://cloud.githubusercontent.com/assets/8946022/18083667/a4ca0496-6ed6-11e6-82c7-ba92149307c9.png)

i am a new ,i don not know why your ios folder is no .xcodeproj file.

**Comment by narayananvenk** [comment]
Did you try the steps in my earlier message?
